version: '3.3'
services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: docker/local/mysql/Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: "redis:7.2-alpine"
    ports:
      - "6379:6379"
      
volumes:
  db_data: